version: '2'
services:
    mosquitto:
        image: eamonford/mosquitto
        ports:
            - "1883:1883"
    ingestor:
        image: eamonford/ingestor
        depends_on:
            - postgres
            - mosquitto
        environment:
            - MQTT_HOST=mosquitto
            - PG_HOST=postgres
    persistor:
        image: eamonford/persistor
        depends_on:
            - influxdb
            - postgres
            - mosquitto
        environment:
            - INFLUXDB_HOST=influxdb
            - POSTGRES_HOST=postgres
            - MQTT_HOST=mosquitto
    dashboard:
        image: fg2it/grafana-armhf:v3.1.1
        depends_on:
            - influxdb
        ports:
            - "3000:3000"
        environment:
            - VIRTUAL_HOST=localhost
    influxdb:
        image: eamonford/rpi-influxdb
        ports:
            - "8086:8086"
            - "8083:8083"
        environment:
            - DB_NAME=dionysus_readings
    postgres:
        image: eamonford/rpi-postgres
        ports:
            - "5432:5432"
        environment:
            - DB_USER=admin
            - DB_PASS=password
            - DB_NAME=database
    irrigator:
        image: eamonford/irrigator
        environment:
            - MQTT_HOST: mosquitto
            - PG_HOST: postgres
